Problem Statement : Hospital Patient Data Analysis
Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.
Tasks:
1.	Load the patient dataset and show summary with info().
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
4.	Use groupby to find total bill amount per department.
5.	Remove duplicate patient records based on PatientID.
6.	Fill missing BillAmount values with the mean bill amount.
7.	Merge the billing dataset with patient dataset on PatientID.
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).
Expected Outcome:
•	Final cleaned dataset with accurate billing info.
•	All missing values handled, merged dataset across PatientID.
•	Ability to perform further analytics on department-wise revenue or doctor performance.

In [236]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [237]:
Patients = pd.read_csv('Patient_Data.csv')
Billing = pd.read_csv('Billing_Data.csv')

In [238]:
Billing

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [239]:
Patients

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [240]:
Patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [241]:
Billing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [242]:
num_col1 = Patients.select_dtypes('int','float').columns
cat_col1 = Patients.select_dtypes('object').columns
num_col2= Billing.select_dtypes('int','float').columns
print('numerical columns of patient data:',num_col1)
print('categorical columns of patient data:',cat_col1)
print('numerical columns of billing data:',num_col2)

numerical columns of patient data: Index(['PatientID', 'ReceptionistID'], dtype='object')
categorical columns of patient data: Index(['Name', 'Department', 'Doctor', 'CheckInTime'], dtype='object')
numerical columns of billing data: Index(['PatientID', 'InsuranceCovered', 'FinalAmount'], dtype='object')

In [243]:
P_billing = Patients[['PatientID','Department','Doctor']]
P_billing

   PatientID   Department     Doctor
0        101   Cardiology  Dr. Smith
1        102    Neurology   Dr. John
2        103  Orthopedics    Dr. Lee
3        104   Cardiology  Dr. Smith
4        105  Dermatology   Dr. Rose
5        101   Cardiology  Dr. Smith

In [244]:
P_billing1 = Billing[['FinalAmount']]
P_billing1

   FinalAmount
0         3000
1         3500
2         5000
3         3200
4         4000

In [245]:
droped_col= Patients.drop(['ReceptionistID','CheckInTime'],axis=1)
droped_col

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [246]:
dep_bill= Billing.groupby('PatientID')['FinalAmount'].sum().reset_index()
dep_bill = pd.merge(dep_bill,Patients[['PatientID','Department']],on='PatientID')
dep_total = dep_bill.groupby('Department')['FinalAmount'].sum().reset_index()
dep_total

    Department  FinalAmount
0   Cardiology         9200
1  Dermatology         4000
2    Neurology         3500
3  Orthopedics         5000

In [247]:
droped_col1= droped_col.drop_duplicates(subset='PatientID')
droped_col1

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [248]:
mean_final=droped_col1['BillAmount'].mean()
print(mean_final)

6233.333333333333

In [249]:
droped_col1['BillAmount'].fillna(mean_final,inplace=True)
droped_col1

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [250]:
merged=pd.merge(droped_col1,Billing,on='PatientID')
merged

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [251]:
new_patient = pd.DataFrame({'PatientID': [111,112],
                            'Name':['alvin','Tom'],
                            'Department':['cardiology','neurology'],
                            'Doctor':['Dr.jorge','Dr.sharma']
                           })

In [252]:
new_patient

   PatientID   Name  Department     Doctor
0        111  alvin  cardiology   Dr.jorge
1        112    Tom   neurology  Dr.sharma

In [257]:
new_billing_col = pd.DataFrame({ 'BillAmount':[4500,3400],
                            'InsuranceCovered':[1500,2000],
                            'FinalAmount':[3000,1400]})
new_billing_col

   BillAmount  InsuranceCovered  FinalAmount
0        4500              1500         3000
1        3400              2000         1400

In [259]:
new_patients_full = pd.concat([new_patient,new_billing_col],axis=1)
new_patients_full

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,111,alvin,cardiology,Dr.jorge,4500,1500,3000
1,112,Tom,neurology,Dr.sharma,3400,2000,1400

In [260]:
final_data = pd.concat([merged,new_patients_full],axis=0,ignore_index=True)
final_data

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000
5,111,alvin,cardiology,Dr.jorge,4500.000000,1500,3000
6,112,Tom,neurology,Dr.sharma,3400.000000,2000,1400